### PR TITLE
fix: disable write after stream destoryed

### PR DESCRIPTION
**Pull request by JiangWeixian**
Closed: #20

### CODE REVIEW

**Comment by JiangWeixian** [comment]
@brillout cc

**Comment by brillout** [comment]
Shouldn't we destroy `writableForReact`?

**Comment by brillout** [comment]
(If that's even possible?)

**Comment by JiangWeixian** [comment]
I test write `writableForReact.destroy()` inside 

```diff
destroy(err) {
  debug(`destroy (\`!!err === ${!!err}\`)`)
  // Upon React internal errors (i.e. React bugs), React destroys the stream.
  if (err) onReactBug(err)
  writableFromUser.destroy(err ?? undefined)
+  writableForReact.destroy()
  onEnded()
}
```

No error will be throwed.

**Comment by brillout** [comment]
Wonderful.

**Comment by brillout** [comment]
Fix released in `0.3.11`. FYI cb0d1ee346566eb1814821a81267f71b93997a5c.

**Comment by brillout** [comment]
Btw. I'm curious: what are you using `react-streaming` for?

**Comment by JiangWeixian** [comment]
I maintain a private framework package. There is API request cost lots time in client-side. I move this request into server-side to improve LCP metric.

**Comment by brillout** [comment]
Sounds neat, btw. https://github.com/sponsors/brillout.

**Comment by brillout** [comment]
Thanks 💚. Next step being to convince your employer :-).

**Pull request merged**
